const $=id=>document.getElementById(id);let items=[],current=null;const api=async(url,options={})=>{const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Ocurrió un error");return b};
async function start(){const s=await api("/api/admin-auth");if(s.authenticated)return showApp();$("loginView").hidden=false;if(!s.configured){$("loginMessage").textContent="Falta configurar la contraseña administrativa en Vercel.";$("loginMessage").className="message error"}}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin-auth",{method:"POST",body:JSON.stringify({password:$("password").value})});showApp()}catch(x){$("loginMessage").textContent=x.message;$("loginMessage").className="message error"}};
async function showApp(){$("loginView").hidden=true;$("appView").hidden=false;await load()}
async function load(){try{items=(await api("/api/admin-catalog")).items;render()}catch(e){alert(e.message)}}
function filtered(){const q=$("adminSearch").value.toLowerCase(),cat=$("categoryFilter").value,status=$("statusFilter").value;return items.filter(p=>(!q||`${p.Title} ${p.marca}`.toLowerCase().includes(q))&&(!cat||p.categoria===cat)&&(status==="all"||(status==="deleted"?p.deleted:!p.deleted)))}
function render(){const list=filtered();$("summary").textContent=`${items.filter(x=>!x.deleted).length.toLocaleString("es")} activos · ${items.length.toLocaleString("es")} registros`;$("inventory").innerHTML="";list.forEach(p=>{const row=document.createElement("article");row.className="row";row.innerHTML=`<img src="${escapeHtml(p.Image)}" onerror="this.src='/assets/placeholder.webp'"><div><strong>${escapeHtml(p.Title)}</strong><small>${escapeHtml(p.marca||"Otros")}</small></div><span class="pill">${escapeHtml(p.categoria||p.tipo||"Sin categoría")}</span><small>${p.entregaInmediata?"Entrega inmediata":"Catálogo"}</small><small>${p.deleted?"Desactivado":"Editar →"}</small>`;row.onclick=()=>openEditor(p);$("inventory").appendChild(row)});$("emptyState").hidden=!!list.length}
function escapeHtml(v){return String(v||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
["adminSearch","categoryFilter","statusFilter"].forEach(id=>$(id).oninput=render);
function openEditor(p=null){current=p;$("editorTitle").textContent=p?"Editar perfume":"Nuevo perfume";$("productId").value=p?.id||"";$("productTitle").value=p?.Title||"";$("productImage").value=p?.Image||"";$("productBrand").value=p?.marca||"";$("productCategory").value=p?.categoria||"Unisex";$("productType").value=p?.tipo||"";$("productDescription").value=p?.descripcion||"";$("productImmediate").checked=!!p?.entregaInmediata;$("imagePreview").src=p?.Image||"/assets/placeholder.webp";$("deleteButton").hidden=!p;$("deleteButton").textContent=p?.deleted?"Reactivar":"Desactivar";$("editorMessage").textContent="";$("editorDialog").showModal()}
$("newButton").onclick=()=>openEditor();$("closeEditor").onclick=()=>$("editorDialog").close();$("productImage").oninput=()=>$("imagePreview").src=$("productImage").value||"/assets/placeholder.webp";
$("imageFile").onchange=async()=>{const file=$("imageFile").files[0];if(!file)return;if(file.size>4e6)return alert("La imagen supera 4 MB");$("editorMessage").textContent="Subiendo imagen…";try{const data=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result.split(",")[1]);r.onerror=no;r.readAsDataURL(file)});const out=await api("/api/admin-upload",{method:"POST",body:JSON.stringify({name:file.name,contentType:file.type,data})});$("productImage").value=out.url;$("imagePreview").src=out.url;$("editorMessage").textContent="Imagen lista"}catch(e){$("editorMessage").textContent=e.message;$("editorMessage").className="message error"}};
function payload(){return{id:$("productId").value||undefined,Title:$("productTitle").value,Image:$("productImage").value,marca:$("productBrand").value,categoria:$("productCategory").value,tipo:$("productType").value||$("productCategory").value,descripcion:$("productDescription").value,entregaInmediata:$("productImmediate").checked,deleted:current?.deleted||false}}
$("editorForm").onsubmit=async e=>{e.preventDefault();$("editorMessage").textContent="Guardando…";try{await api("/api/admin-catalog",{method:"POST",body:JSON.stringify(payload())});$("editorDialog").close();await load()}catch(x){$("editorMessage").textContent=x.message;$("editorMessage").className="message error"}};
$("deleteButton").onclick=async()=>{if(!current)return;const p={...payload(),deleted:!current.deleted};if(!confirm(p.deleted?"¿Desactivar este perfume?":"¿Reactivar este perfume?"))return;await api("/api/admin-catalog",{method:"POST",body:JSON.stringify(p)});$("editorDialog").close();await load()};
$("logoutButton").onclick=async()=>{await api("/api/admin-auth",{method:"DELETE"});location.reload()};start().catch(e=>{$("loginMessage").textContent=e.message});
