const $=id=>document.getElementById(id);
async function api(options={}){const response=await fetch("/api/partner-auth",{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"No se pudo completar la solicitud");return body}
function message(id,text,type=""){const el=$(id);el.textContent=text;el.className=`message ${type}`}
function showAuth(register=false){$("authView").hidden=false;$("profileView").hidden=true;$("loginForm").hidden=register;$("registerForm").hidden=!register;$("loginTab").classList.toggle("active",!register);$("registerTab").classList.toggle("active",register);message("authMessage","")}
function showProfile(profile){$("authView").hidden=true;$("profileView").hidden=false;$("profileName").textContent=profile.name;$("profilePhone").value=profile.phone;const link=new URL(profile.link,location.origin).href;$("profileLink").value=link;$("openCatalog").href=link;$("profilePassword").value="";message("profileMessage","")}
$("loginTab").onclick=()=>showAuth(false);$("registerTab").onclick=()=>showAuth(true);
$("loginForm").onsubmit=async event=>{event.preventDefault();message("authMessage","Ingresando…");try{const out=await api({method:"POST",body:JSON.stringify({action:"login",username:$("loginUsername").value,password:$("loginPassword").value})});showProfile(out.profile)}catch(error){message("authMessage",error.message,"error")}};
$("registerForm").onsubmit=async event=>{event.preventDefault();message("authMessage","Creando tu enlace…");try{const out=await api({method:"POST",body:JSON.stringify({action:"register",name:$("registerName").value,username:$("registerUsername").value,phone:$("registerPhone").value,password:$("registerPassword").value})});showProfile(out.profile)}catch(error){message("authMessage",error.message,"error")}};
$("profileForm").onsubmit=async event=>{event.preventDefault();message("profileMessage","Guardando…");try{const out=await api({method:"PUT",body:JSON.stringify({phone:$("profilePhone").value,password:$("profilePassword").value})});showProfile(out.profile);message("profileMessage","Cambios guardados","success")}catch(error){message("profileMessage",error.message,"error")}};
$("copyLink").onclick=async()=>{try{await navigator.clipboard.writeText($("profileLink").value);message("profileMessage","Enlace copiado","success")}catch{$("profileLink").select();document.execCommand("copy")}};
$("logoutButton").onclick=async()=>{await api({method:"DELETE"});showAuth(false)};
api().then(out=>out.authenticated?showProfile(out.profile):showAuth(false)).catch(error=>message("authMessage",error.message,"error"));
